repo_url: https://usa-reddragon.github.io/mattermost-android/repo
repo_name: McSwain Mattermost F-Droid repo
repo_description: This is a custom F-Droid repository for the McSwain Mattermost app.
archive_url: https://usa-reddragon.github.io/mattermost-android/archive
archive_name: McSwain Mattermost F-Droid archive
archive_description: This is a custom F-Droid archive for the McSwain Mattermost app.
archive_older: 5
local_copy_dir: /home/runner/work/fdroid

keystore: keystore.jks
repo_keyalias: localhost.localdomain
keydname: CN=localhost.localdomain, OU=F-Droid
keypass: {env: FDROID_KEYPASS}
keystorepass: {env: FDROID_KEY_STORE_PASS}
virustotal_apikey: {env: VIRUSTOTAL_APIKEY}
