repo_url: https://calyxos.gitlab.io/calyx-fdroid-repo/fdroid/repo
repo_name: McSwain Mattermost F-Droid repo
repo_icon: fdroid-icon.png
repo_description: This is a custom F-Droid repository for the McSwain Mattermost app.
archive_older: 0
local_copy_dir: out

keystore: ../keystore.jks
repo_keyalias: localhost.localdomain
keydname: CN=localhost.localdomain, OU=F-Droid
keypass: {env: FDROID_KEYPASS}
keystorepass: {env: FDROID_KEY_STORE_PASS}
virustotal_apikey: {env: VIRUSTOTAL_APIKEY}
