on:
  release:
    types:
      - released

concurrency:
  group: "pages"
  cancel-in-progress: false

permissions:
  id-token: write
  pages: write

jobs:
  fdroid:
    environment:
      name: github-pages
      url: ${{ steps.fdroid.outputs.page_url }}
    runs-on: ubuntu-22.04
    steps:
    - name: Checkout fdroid branch
      uses: actions/checkout@v4
      with:
        ref: fdroid
        fetch-depth: 0

    - name: Install fdroid server
      run: |
        echo -n '${{ secrets.FDROID_KEYSTORE }}' | base64 -d > keystore.jks
        chmod 600 keystore.jks config.yml
        mkdir -p repo
        sudo add-apt-repository ppa:fdroid/fdroidserver
        sudo apt-get update
        sudo apt-get install fdroidserver

    - name: Download apk
      uses: robinraju/release-downloader@v1
      with:
        tag: "${{ github.event.release.tag_name }}"
        latest: true
        fileName: "Mattermost.apk"

    - name: Move apk to fdroid
      run: mv Mattermost.apk repo/dev.mcswain.mattermost-${{ github.event.release.tag_name }}.apk

    - name: Run fdroid update
      run: |
        fdroid update --pretty
        mkdir /home/runner/work/fdroid
        fdroid deploy
      env:  
        FDROID_KEYPASS: "${{ secrets.FDROID_KEY_PASSWORD }}"
        FDROID_KEY_STORE_PASS: "${{ secrets.FDROID_KEY_STORE_PASS }}"
        VIRUSTOTAL_APIKEY: "${{ secrets.VIRUSTOTAL_APIKEY }}"

    - name: Commit repo
      run: |
        git config user.name "github-actions[bot]"
        git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
        git commit -m "Mattermost ${{ github.event.release.tag_name }}" .
        git reset $(git commit-tree HEAD^{tree} -m "Mattermost ${{ github.event.release.tag_name }}")
        git push --force origin HEAD:refs/heads/fdroid

    - name: Setup Pages
      uses: actions/configure-pages@v5

    - name: Upload artifact
      uses: actions/upload-pages-artifact@v3
      with:
        path: '/home/runner/work/fdroid/'

    - name: Deploy to GitHub Pages
      id: deployment
      uses: actions/deploy-pages@v4

    - name: Shred keystore
      if: always()
      run: |
        shred -n 5 -f keystore.jks || true 
