on:
  release:
    types:
      - released
  workflow_dispatch:

jobs:
  fdroid:
    runs-on: ubuntu-22.04
    steps:
    - name: Checkout fdroid branch
      uses: actions/checkout@v4
      with:
        ref: fdroid
        fetch-depth: 0

    - name: Install fdroid server
      run: |
        echo ${FDROID_KEYSTORE} | base64 -d > keystore.jks
        chmod 600 fdroid/config.py keystore.jks
        echo "keypass=\"${FDROID_KEYPASS}\"" >>config.py
        echo "keystorepass=\"${FDROID_KEYSTOREPASS}\"" >>config.py
        mkdir -p fdroid/repo
        sudo add-apt-repository ppa:fdroid/fdroidserver
        sudo apt-get update
        sudo apt-get install fdroidserver
      env:
        FDROID_KEYSTORE: "${{ secrets.FDROID_KEYSTORE }}"
        FDROID_KEYPASS: "${{ secrets.FDROID_KEYSTORE_PASSWORD }}"
        FDROID_KEYSTOREPASS: "${{ secrets.FDROID_KEYSTORE_PASSWORD }}"

    - name: Download apk
      uses: robinraju/release-downloader@v1
      with:
        tag: "${{ github.event.release.tag_name }}"
        latest: true
        fileName: "Mattermost.apk"

    - name: Move apk to fdroid
      run: mv Mattermost.apk fdroid/repo/dev.mcswain.mattermost-${{ github.event.release.tag_name }}.apk

    - name: Shred keystore and config
      if: always()
      run: |
        shred -n 5 -f keystore.jks || true
        shred -n 5 -f fdroid/config.py || true  
